name: mobile_scan_qr
description: A universal barcode and QR code scanner for Flutter based on MLKit. Uses CameraX on Android, AVFoundation on iOS.
version: 5.0.1
repository: https://github.com/jawa0919/mobile_scan_qr
homepage: https://github.com/jawa0919/mobile_scan_qr

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: top.jawa0919.mobile_scan_qr
        pluginClass: MobileScannerPlugin
      ios:
        pluginClass: MobileScannerPlugin
